### PR TITLE
Fix restrict incompatible ox version

### PR DESCRIPTION
**Pull request by choosen**
After last update we got error in out test suite:

```
Finished in 0.003121s, 3204.1012 runs/s, 5126.5620 assertions/s.

  1) Failure:
ToxTest#test_simple_el_wrapped_empty [/Users/piotrwasiak/Prj/prograils/tox/test/tox_test.rb:680]:
Expected: ""
  Actual: "<name>你好世界</name>"
```

Content in this example is initially : 
```
%{
        <something/>
      },
```

### CODE REVIEW

**Comment by challengee** [comment]
Thanks! Do you know why it is failing with a newer ox version?

**Comment by devwout** [comment]
Looks like a bug introduced in the latest version of `ox`. When changing `pretty: true` in the tests (which will leave the `indent` setting be, the tests pass reliably.

```
diff --git a/test/tox_test.rb b/test/tox_test.rb
index eae63fc..c30fb4d 100644
--- a/test/tox_test.rb
+++ b/test/tox_test.rb
@@ -674,7 +674,7 @@ class ToxTest < Minitest::Test
     template = Tox::Template.dsl(&template)
     assert_equal(
       scrub(xml),
-      scrub(template.render(value, pretty: false))
+      scrub(template.render(value, pretty: true))
     )
   end
```

**Comment by choosen** [comment]
issue which was introduced with last changes : 
https://github.com/ohler55/ox/issues/215

**Comment by choosen** [comment]
`dump_obj_to_xml(VALUE obj, Options copts, Out out) {`
...
```
if (0 >= out->indent) {
	  dump_value(out, "\n", 1);
    }
```
When I changed the condition direction it works well. 
They said in issue that they should not dump if indent is negative number , but they do it on positive numbers.

**Comment by devwout** [comment]
Yes that seems to be it. Make a PR? Should it be `>=` or just `>`?

**Comment by choosen** [comment]
hmm 
they tend to be right with that direction ..  I saw it wrong.
So why do we get previous dump value if we do not dump anything ?

**Comment by choosen** [comment]
```
    if (0 <= out->indent) {
	  dump_value(out, "\n", 1);
    } else {
	  dump_value(out, "", 0);
	}
```
dumping empty value with size = 0  
fixes the bug

**Comment by choosen** [comment]
I will create an PR

**Comment by choosen** [comment]
OX issue fix is in master. 

So we can be almost certain that it will be in next release

**Pull request merged**
